# -*- coding: utf-8 -*-
"""Space_Missions_Analysis_(start).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gRgcpiowi4liWSrkKyb7fwHcquKFnVS

# Introduction

<center><img src="https://i.imgur.com/9hLRsjZ.jpg" height=400></center>

This dataset was scraped from [nextspaceflight.com](https://nextspaceflight.com/launches/past/?page=1) and includes all the space missions since the beginning of Space Race between the USA and the Soviet Union in 1957!

### Install Package with Country Codes
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install iso3166

"""### Upgrade Plotly

Run the cell below if you are working with Google Colab.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade plotly

"""### Import Statements"""

import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# These might be helpful:
from iso3166 import countries
from datetime import datetime, timedelta

"""### Notebook Presentation"""

pd.options.display.float_format = '{:,.2f}'.format

"""### Load the Data"""

df_data = pd.read_csv('mission_launches.csv')

"""# Preliminary Data Exploration

* What is the shape of `df_data`?
* How many rows and columns does it have?
* What are the column names?
* Are there any NaN values or duplicates?
"""

df_data.shape

df_data.columns

print(df_data)

"""## Data Cleaning - Check for Missing Values and Duplicates

Consider removing columns containing junk data.
"""

print(df_data.isna().values.any())

print(df_data.duplicated().values.any())

df_data = df_data.dropna()
print(df_data)

"""## Descriptive Statistics"""

df_data.describe()

"""# Number of Launches per Company

Create a chart that shows the number of space mission launches by organisation.
"""

mission_by_org = df_data["Organisation"].value_counts().reset_index()
mission_by_org.columns = ['Organization', 'Space Mission Count']
print(mission_by_org)

plt.figure(figsize=(14, 6))
plt.bar(mission_by_org['Organization'], mission_by_org['Space Mission Count'])
plt.xticks(rotation=90)
plt.title("Space Mission Launches by Organisations")
plt.ylabel("Space Mission Count")
plt.show()

"""# Number of Active versus Retired Rockets

How many rockets are active compared to those that are decomissioned?
"""

rocket_status = df_data["Rocket_Status"].value_counts().reset_index()
rocket_status.columns = ['Rocket_Status', 'Count']
print(rocket_status)

plt.figure(figsize=(14, 6))
plt.bar(rocket_status['Rocket_Status'], rocket_status['Count'])
plt.xticks(rotation=90)
plt.title("Rockets Status")
plt.ylabel("Count")
plt.show()

"""# Distribution of Mission Status

How many missions were successful?
How many missions failed?
"""

mission_status = df_data["Mission_Status"].value_counts().reset_index()
mission_status.columns = ['Mission_Status', 'Count']
print(mission_status)

plt.figure(figsize=(14, 6))
plt.bar(mission_status['Mission_Status'], mission_status['Count'])
plt.xticks(rotation=90)
plt.title("Mission Status")
plt.ylabel("Count")
plt.show()

"""# How Expensive are the Launches?

Create a histogram and visualise the distribution. The price column is given in USD millions (careful of missing values).
"""

print(df_data['Price'].isnull())

df_data = df_data.dropna(subset=['Price'])
# Convert to numbers just in case
df_data['Price'] = pd.to_numeric(df_data['Price'], errors='coerce')

plt.figure(figsize=(8,4), dpi=200)
sns.histplot(data=df_data, x='Price', bins=30, kde=True)
plt.title('Price Distribution of Mission Launches', fontsize=14)
plt.xlabel('Price', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.show()

"""# Use a Choropleth Map to Show the Number of Launches by Country

* Create a choropleth map using [the plotly documentation](https://plotly.com/python/choropleth-maps/)
* Experiment with [plotly's available colours](https://plotly.com/python/builtin-colorscales/). I quite like the sequential colour `matter` on this map.
* You'll need to extract a `country` feature as well as change the country names that no longer exist.

Wrangle the Country Names

You'll need to use a 3 letter country code for each country. You might have to change some country names.

* Russia is the Russian Federation
* New Mexico should be USA
* Yellow Sea refers to China
* Shahrud Missile Test Site should be Iran
* Pacific Missile Range Facility should be USA
* Barents Sea should be Russian Federation
* Gran Canaria should be USA


You can use the iso3166 package to convert the country names to Alpha3 format.
"""

df_data["Country"] = df_data['Location'].apply(lambda x: x.split(",")[-1].strip())
print(df_data)

country_corrections = {"Russia": "Russian Federation",
    "New Mexico": "USA",
    "Yellow Sea": "China",
    "Shahrud Missile Test Site": "Iran",
    "Pacific Missile Range Facility": "USA",
    "Barents Sea": "Russian Federation",
    "Gran Canaria": "USA",
    "Kazakhstan": "Kazakhstan",
    "USA": "United States of America",
    "United States": "United States of America",}

df_data['Country'] = df_data['Country'].replace(country_corrections)
print(df_data)

def get_alpha3(name):
  try:
    return countries.get(name).alpha3
  except:
    return None

df_data["ISO"] = df_data['Country'].apply(get_alpha3)

df_data[['Location', 'Country', 'ISO']].head(10)

country_counts = df_data.groupby(["Country", "ISO"]).size().reset_index(name="Launch_Count")
print(country_counts)

fig = px.choropleth(
    country_counts,
    locations="ISO",
    color="Launch_Count",
    hover_name="Country",
    color_continuous_scale="matter",
    title="Number of Space Launches by Country"
)

fig.show()

"""# Use a Choropleth Map to Show the Number of Failures by Country

"""

failures = df_data[df_data["Mission_Status"] == "Failure"]
print(failures)

failures_by_country = (failures.groupby(["Country", "ISO"]).size().reset_index(name="Failure_Count"))
print(failures_by_country)

fig = px.choropleth(
    failures_by_country,
    locations="ISO",
    color="Failure_Count",
    hover_name="Country",
    color_continuous_scale="matter",
    title="Number of Failed Space Launches by Country"
)

fig.show()

"""# Create a Plotly Sunburst Chart of the countries, organisations, and mission status."""

fig = px.sunburst(
    df_data,
    path=["Country", "Organisation", "Mission_Status"],
    title="Sunburst Chart: Country → Organisation → Mission Status",
)

fig.show()

"""# Analyse the Total Amount of Money Spent by Organisation on Space Missions"""

df_price = df_data.dropna(subset=["Price"])
money_spent = df_price.groupby("Organisation")["Price"].sum().reset_index().sort_values(by="Price", ascending=False)
print(money_spent)

fig = px.bar(
    money_spent,
    x="Price",
    y="Organisation",
    orientation="h",
    color="Price",
    color_continuous_scale="matter",
    title="Total Amount of Money Spent by Organisation on Space Missions (in USD Millions)",
)

fig.show()

"""# Analyse the Amount of Money Spent by Organisation per Launch"""

df_price = df_data.dropna(subset=["Price"])
money_spent_per_launch = df_price.groupby("Organisation")["Price"].mean().reset_index().sort_values(by="Price", ascending=False)
print(money_spent_per_launch)

fig = px.bar(
    money_spent_per_launch,
    x="Organisation",
    y="Price",
    color="Price",
    color_continuous_scale="matter",
    title="Average Amount Spent by Organisation per Launch (USD Millions)",
)

fig.show()

"""# Chart the Number of Launches per Year"""

df_data['date'] = pd.to_datetime(df_data['Date'], errors='coerce')
df_data['year'] = df_data['date'].dt.year
df_data['year'] = df_data['year'].astype("Int64")

launches_per_year = df_data.groupby("year").size().reset_index(name="Launch_Count").sort_values(by="year")
print(launches_per_year)

fig = px.line(
    launches_per_year,
    x="year",
    y="Launch_Count",
    title="Number of Space Launches per Year",
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Number of Launches",
)

fig.show()

"""# Chart the Number of Launches Month-on-Month until the Present

Which month has seen the highest number of launches in all time? Superimpose a rolling average on the month on month time series chart.
"""

df_data['date'] = pd.to_datetime(df_data['Date'], errors='coerce')
df_data['month'] = df_data['date'].dt.month
df_data['month'] = df_data['month'].astype("Int64")

launches_per_month = df_data.groupby("month").size().reset_index(name="Launch_Count").sort_values(by="month")
print(launches_per_month)

# Convert month numbers to datetime objects (use dummy year 2025 for clarity)
launches_per_month['month_date'] = launches_per_month['month'].apply(lambda m: datetime(2025, int(m), 1))
print(launches_per_month)

launches_per_month['Rolling_Avg'] = launches_per_month['Launch_Count'].rolling(window=2, min_periods=1).mean()
print(launches_per_month)

plt.figure(figsize=(14, 8), dpi=120)
plt.title("Space Launches Month-on-Month (with 3-Month Rolling Average)", fontsize=18)

# Axis formatting
ax = plt.gca()

# --- Add small timedelta padding to x-axis ---
start_date = launches_per_month['month_date'].min() - timedelta(days=15)
end_date = launches_per_month['month_date'].max() + timedelta(days=15)
ax.set_xlim([start_date, end_date])

# --- Plot actual monthly launches ---
plt.plot(
    launches_per_month['month_date'],
    launches_per_month['Launch_Count'],
    color='skyblue',
    linewidth=2,
    marker='o',
    label='Monthly Launches'
)

# --- Plot rolling average ---
plt.plot(
    launches_per_month['month_date'],
    launches_per_month['Rolling_Avg'],
    color='crimson',
    linewidth=3,
    linestyle='--',
    label='Month-on-Month Rolling Average'
)

# Beautify
plt.xlabel("Month", fontsize=14)
plt.ylabel("Number of Launches", fontsize=14)
plt.xticks(launches_per_month['month_date'], rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.grid(color='grey', linestyle='--', alpha=0.6)
plt.legend(fontsize=13)
plt.tight_layout()

plt.show()

"""# Launches per Month: Which months are most popular and least popular for launches?

Some months have better weather than others. Which time of year seems to be best for space missions?
"""

# Convert month numbers to names for readability
launches_per_month['Month_Name'] = launches_per_month['month'].apply(lambda x: datetime(2025, x, 1).strftime('%b'))
print(launches_per_month)

plt.figure(figsize=(12,6), dpi=120)
sns.barplot(data=launches_per_month, x='Month_Name', y='Launch_Count', palette='coolwarm')

plt.title("🚀 Number of Space Launches per Month", fontsize=18)
plt.xlabel("Month", fontsize=14)
plt.ylabel("Number of Launches", fontsize=14)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""# How has the Launch Price varied Over Time?

Create a line chart that shows the average price of rocket launches over time.
"""

# Ensure date column is parsed properly
df_data['date'] = pd.to_datetime(df_data['Date'], errors='coerce')

# Extract year
df_data['year'] = df_data['date'].dt.year
df_data['year'] = df_data['year'].astype("Int64")

# Clean 'Price' column (remove commas or non-numeric values)
df_data['Price'] = (df_data['Price'].replace('[\$,]', '', regex=True).astype(float))

# Group by year and calculate average launch price
price_over_time = (df_data.groupby('year')['Price'].mean().reset_index(name='Average_Price').dropna())
print(price_over_time)

plt.figure(figsize=(14, 7), dpi=120)
plt.plot(
    price_over_time['year'],
    price_over_time['Average_Price'],
    color='mediumseagreen',
    linewidth=3,
    marker='o',
    label='Average Launch Price'
)

plt.title("Average Rocket Launch Price Over Time", fontsize=18)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Average Price (USD Millions)", fontsize=14)
plt.grid(color='grey', linestyle='--', alpha=0.6)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()

"""# Chart the Number of Launches over Time by the Top 10 Organisations.

How has the dominance of launches changed over time between the different players?
"""

top_10_orgs = df_data['Organisation'].value_counts().head(10).index
print(top_10_orgs)

top_org_data = df_data[df_data['Organisation'].isin(top_10_orgs)]
print(top_org_data)

launches_by_org = top_org_data.groupby(['year', 'Organisation']).size().reset_index(name='Launch_Count')
print(launches_by_org)

launches_pivot = launches_by_org.pivot(index='year', columns='Organisation', values='Launch_Count').fillna(0)
print(launches_pivot)

plt.figure(figsize=(14, 8), dpi=120)
for org in launches_pivot.columns:
    plt.plot(
        launches_pivot.index,
        launches_pivot[org],
        marker='o',
        linewidth=2,
        label=org
    )

plt.title("🚀 Number of Launches Over Time by Top 10 Organisations", fontsize=18)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Number of Launches", fontsize=14)
plt.grid(color='grey', linestyle='--', alpha=0.5)
plt.legend(title="Organisation", fontsize=10, bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""# Cold War Space Race: USA vs USSR

The cold war lasted from the start of the dataset up until 1991.
"""

cold_war_data = df_data[df_data['year'] <= 1991]
print(cold_war_data)

cold_war_data['Country'] = cold_war_data['Location'].apply(lambda x: str(x).split(',')[-1].strip())

cold_war_data['Country'] = cold_war_data['Country'].replace({
    'USA': 'United States',
    'USSR': 'Soviet Union',
    'Russian Federation': 'Soviet Union'
})

# Keep only USA and USSR
cold_war_data = cold_war_data[cold_war_data['Country'].isin(['United States', 'Soviet Union'])]

launches_by_year = (cold_war_data.groupby(['year', 'Country']).size().reset_index(name='Launch_Count'))
print(launches_by_year)

plt.figure(figsize=(12, 7), dpi=120)
for country in launches_by_year['Country'].unique():
    subset = launches_by_year[launches_by_year['Country'] == country]
    plt.plot(subset['date'], subset['Launch_Count'], marker='o', linewidth=2, label=country)

plt.title("🚀 Cold War Space Race: USA vs USSR (Launches Until 1991)", fontsize=18)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Number of Launches", fontsize=14)
plt.legend(title="Country", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""## Create a Plotly Pie Chart comparing the total number of launches of the USSR and the USA

Hint: Remember to include former Soviet Republics like Kazakhstan when analysing the total number of launches.
"""

df_data['Country'] = df_data['Location'].apply(lambda x: str(x).split(',')[-1].strip())

df_data['Country'] = df_data['Country'].replace({
    'USA': 'United States',
    'USSR': 'Soviet Union',
    'Russian Federation': 'Soviet Union',
    'Kazakhstan': 'Soviet Union',  # ✅ Include former USSR states
    'Ukraine': 'Soviet Union',
    'Belarus': 'Soviet Union'
})

print(df_data)

cold_war_data = df_data[df_data['Country'].isin(['United States', 'Soviet Union'])]
print(cold_war_data)

launch_counts = (
    cold_war_data.groupby('Country')
    .size()
    .reset_index(name='Launch_Count')
)

print(launch_counts)

fig = px.pie(
    launch_counts,
    names='Country',
    values='Launch_Count',
    title='Total Launches: USA vs USSR (Including Former Soviet Republics)',
    color='Country',
    color_discrete_map={'United States': 'blue', 'Soviet Union': 'red'}
)

fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

"""## Create a Chart that Shows the Total Number of Launches Year-On-Year by the Two Superpowers"""

df_data['Country'] = df_data['Location'].apply(lambda x: str(x).split(',')[-1].strip())

df_data['Country'] = df_data['Country'].replace({
    'USA': 'United States',
    'USSR': 'Soviet Union',
    'Russian Federation': 'Soviet Union',
    'Kazakhstan': 'Soviet Union',  # ✅ Include former USSR states
    'Ukraine': 'Soviet Union',
    'Belarus': 'Soviet Union'
})

print(df_data)

cold_war_data = df_data[df_data['Country'].isin(['United States', 'Soviet Union'])]
print(cold_war_data)

launches_per_year = (
    cold_war_data.groupby(['year', 'Country'])
    .size()
    .reset_index(name='Launch_Count')
)

print(launches_per_year)

plt.figure(figsize=(14, 8), dpi=120)
sns.lineplot(
    data=launches_per_year,
    x='year',
    y='Launch_Count',
    hue='Country',
    palette={'United States': 'blue', 'Soviet Union': 'red'},
    marker='o',
    linewidth=2
)

plt.title("Year-on-Year Launches: USA vs USSR", fontsize=18)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Number of Launches", fontsize=14)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""## Chart the Total Number of Mission Failures Year on Year."""

failures = df_data[df_data['Mission_Status'].str.contains('Failure', case=False, na=False)]
print(failures)

failures_per_year = (
    failures.groupby('year')
    .size()
    .reset_index(name='Failure_Count')
)

print(failures_per_year.head())

plt.figure(figsize=(14, 8), dpi=120)
plt.plot(
    failures_per_year['year'],
    failures_per_year['Failure_Count'],
    marker='o',
    color='crimson',
    linewidth=2
)

plt.title("💥 Year-on-Year Mission Failures", fontsize=18)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Number of Failed Launches", fontsize=14)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""## Chart the Percentage of Failures over Time

Did failures go up or down over time? Did the countries get better at minimising risk and improving their chances of success over time?
"""

total_launches = (
    df_data.groupby('year')
    .size()
    .reset_index(name='Total_Launches')
)
print(total_launches)

failures = df_data[df_data['Mission_Status'].str.contains('Failure', case=False, na=False)]

failures_per_year = (
    failures.groupby('year')
    .size()
    .reset_index(name='Failures')
)

print(failures_per_year)

failure_rate = pd.merge(total_launches, failures_per_year, on='year', how='left')
failure_rate['Failures'] = failure_rate['Failures'].fillna(0)
failure_rate['Failure_Percentage'] = (failure_rate['Failures'] / failure_rate['Total_Launches']) * 100

print(failure_rate)

plt.figure(figsize=(14, 8), dpi=120)
plt.plot(
    failure_rate['year'],
    failure_rate['Failure_Percentage'],
    color='crimson',
    linewidth=2.5,
    marker='o',
    label='Failure %'
)

plt.title("Percentage of Mission Failures Over Time", fontsize=18)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Failure Rate (%)", fontsize=14)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()

"""# For Every Year Show which Country was in the Lead in terms of Total Number of Launches up to and including including 2020)

Do the results change if we only look at the number of successful launches?
"""

launches_by_country = (
    df_data.groupby(['year', 'Country'])
    .size()
    .reset_index(name='Launch_Count')
)

print(launches_by_country)

leaders = (launches_by_country.loc[
    launches_by_country.groupby('year')['Launch_Count'].idxmax()]
           .sort_values('year')
          )
print(leaders)

leaders = leaders[leaders['year'] <= 2020]
print(leaders)

plt.figure(figsize=(14, 7), dpi=120)

sns.lineplot(
    data=leaders,
    x='year',
    y='Launch_Count',
    hue='Country',
    linewidth=2.5,
    marker='o'
)

plt.title('Yearly Leaders in Space Launches (up to 2020)', fontsize=18)
plt.xlabel('Year')
plt.ylabel('Number of Launches')
plt.legend(title='Country', loc='upper left')
plt.grid(True, alpha=0.3)
plt.show()

"""# Create a Year-on-Year Chart Showing the Organisation Doing the Most Number of Launches

Which organisation was dominant in the 1970s and 1980s? Which organisation was dominant in 2018, 2019 and 2020?
"""

org_launches = (
    df_data.groupby(['year', 'Organisation'])
    .size()
    .reset_index(name='Launch_Count')
)

print(org_launches)

top_org_per_year = (
    org_launches.loc[org_launches.groupby('year')['Launch_Count'].idxmax()]
    .sort_values('year')
)
print(top_org_per_year)

plt.figure(figsize=(14, 7), dpi=120)
sns.lineplot(
    data=top_org_per_year,
    x='year',
    y='Launch_Count',
    hue='Organisation',
    marker='o',
    linewidth=2.5
)

plt.title('Dominant Space Organisations Year-on-Year (up to 2020)', fontsize=18)
plt.xlabel('Year')
plt.ylabel('Number of Launches')
plt.legend(title='Organisation', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(alpha=0.3)
plt.show()